site_name: Mercury
site_description: A Python SDK for interacting with BroadWorks OCIP API's (SOAP/TCP).

site_url: "https://mercury-fast-docs.14ip.net/"
repo_url: "https://github.com/fourteen-ip/mercury-ocip-fast"
repo_name: "fourteen-ip/mercury-ocip-fast"
dev_addr: 0.0.0.0:8080
extra_css:
- styles/extra.css

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico

  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: "custom"
    accent: "custom"
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: "custom"
    accent: "custom"
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  font:
    text: "Inter"
    code: "JetBrains Mono"

  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - toc.integrate
  - header.autohide
  - content.code.copy
  - content.code.annotate

nav:
- Overview: index.md
- Commands Reference: commands/
- Mercury: https://mercury-docs.14ip.net
- CLI: https://mercury-cli-docs.14ip.net/

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.magiclink
- pymdownx.snippets
- admonition
- pymdownx.details

plugins:
- search
- gen-files:
    scripts:
    - scripts/generate_command_docs.py
- literate-nav
- minify_html
- mkdocstrings:
    handlers:
      python:
        paths: [ "src" ]
        options:
          show_source: true
          show_signature: true
          docstring_style: google
          selection:
            filters:
            - "!^_"
