name: Lint

on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize

jobs:
    run-linters:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Set up uv
              uses: astral-sh/setup-uv@v6

            - name: Run Ruff linter
              run: uv run ruff check .
